### ISSUE TITLE
Filter Icon Bar

### ISSUE THREAD

**Issue by EthanNValencia** [MattDrennan/GreenworksMap#55]
We need the icon bar to be responsive through mouse clicks. When an icon is clicked a grayscale effect will be implemented on the icon. We also want a tooltip for each icon. 
![iconBar](https://user-images.githubusercontent.com/77355976/152654889-516fa776-d842-4954-bb64-c00e5d760e9c.png)

**Comment by MattDrennan** [comment]
This is completed.
