### ISSUE TITLE
Frontend: Tool Tips for Filter Icons in Desktop View

### ISSUE THREAD

**Issue by EthanNValencia** [MattDrennan/GreenworksMap#88]
The Filter Icons need Tool Tips to show what their Pillar names are. The Tool Tips will appear when the user hovers over the icon with their mouse.

**Comment by EthanNValencia** [comment]
![ToolTip](https://user-images.githubusercontent.com/77355976/160157867-d55a6373-f6f5-4282-81f5-284049ba1af1.png)

**Comment by MattDrennan** [comment]
Done
