### ISSUE TITLE
Frontend: Need Green Works Orlando Image/Icon Positioned on the Map

### ISSUE THREAD

**Issue by EthanNValencia** [MattDrennan/GreenworksMap#95]
The icon should be positioned on the map. The upper left-hand corner might make sense for the desktop view but it probably won't look good for mobile view. For mobile view, it could be centered on the top. 
![image](https://user-images.githubusercontent.com/77355976/160197217-49b50dd6-0f0d-4302-b02e-8e633503bd2c.png)

**Comment by EthanNValencia** [comment]
This is how the mobile view could look. 
![image](https://user-images.githubusercontent.com/77355976/160197610-e3fb4c92-5f27-4184-be63-7d3db2550fac.png)

**Comment by EthanNValencia** [comment]
Icon is located at: https://github.com/MattDrennan/GreenworksMap/blob/master/EcoMap/src/main/webapp/images/greenworks.png

**Comment by MattDrennan** [comment]
Done.
